# Go SCIM Sync Configuration File
# This is an example configuration for bi-directional sync between Google Workspace and Beyond Identity

# Application settings
app:
  log_level: "info"          # Options: debug, info, warn, error
  test_mode: true            # Set to false to perform actual changes

# Google Workspace configuration
google_workspace:
  domain: "byndid-mail.com"                    # Your Google Workspace domain
  super_admin_email: "nmelo@byndid-mail.com"  # Super admin email for impersonation
  service_account_key_path: "./service-account.json"  # Path to service account JSON file

# Beyond Identity configuration  
beyond_identity:
  api_token: ""                                          # Your Beyond Identity API token
  scim_base_url: "https://api.byndid.com/scim/v2"       # SCIM API base URL
  native_api_url: "https://api.byndid.com/v2"           # Native API base URL  
  group_prefix: "GoogleSCIM_"                            # Prefix for created groups

# Synchronization settings
sync:
  groups:                                      # List of Google Workspace groups to sync
    - "scim_test@byndid-mail.com"
    - "engineering@byndid-mail.com"
  enrollment_group_email: "byid-enrolled@byndid-mail.com"  # Google group for BI enrolled users (optional)
  enrollment_group_name: "BYID Enrolled"                   # Display name for enrollment group (optional)
  retry_attempts: 3                            # Number of retry attempts for failed operations
  retry_delay_seconds: 30                      # Delay between retry attempts

# Instructions:
# 1. Copy this file to config.yaml
# 2. Update the values with your actual configuration
# 3. Set your Beyond Identity API token in the api_token field above
# 4. Ensure your service account JSON file is in the correct location
# 5. Run: scim-sync validate-config to test your configuration
# 6. Run: scim-sync run to start synchronization
#
# Bi-directional Sync:
# - GWS → BI: Creates users/groups in Beyond Identity based on Google Workspace groups
# - BI → GWS: Manages enrollment group membership based on Beyond Identity user activation status
# - Users who activate in BI are automatically added to the enrollment_group_email
# - Users who become inactive in BI are automatically removed from the enrollment group